spring: 
	profiles: 
		active:
		-dev
---
spring: 
	profiles: dev
	application: 
		name: microservicecloud-cloud-atguigu-test 
---
spring: 
	profiles: test
	application: 
		name: microservicecloud-config-atguigu-test				